[project]
id = "vylux-self-hosted"
name = "vylux"

[api]
port = 3000
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 5432
major_version = 15

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
