#!/usr/bin/env bash
# VYLUX Setup Script
# Generates .env with all required keys and passwords
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$ROOT_DIR/.env"

echo "=== VYLUX Setup ==="
echo ""

# Generate secrets
PG_PASSWORD=$(openssl rand -hex 16)
KEY_VAULTS_SECRET=$(openssl rand -base64 24 | head -c 32)
AUTH_SECRET=$(openssl rand -base64 24 | head -c 32)

cat > "$ENV_FILE" <<EOF
# VYLUX Environment
# Generated by scripts/setup.sh

# =====================
# Database (single ParadeDB instance)
# =====================
DATABASE_URL=postgresql://postgres:${PG_PASSWORD}@vylux-db:5432/lobehub
PG_PASSWORD=${PG_PASSWORD}

# =====================
# LobeHub
# =====================
REDIS_URL=redis://vylux-redis:6379
KEY_VAULTS_SECRET=${KEY_VAULTS_SECRET}
AUTH_SECRET=${AUTH_SECRET}
APP_URL=http://localhost:3210
INTERNAL_APP_URL=http://localhost:3210

# =====================
# Storage (MinIO)
# =====================
S3_ENDPOINT=http://minio:9000
S3_ACCESS_KEY=admin
S3_SECRET_ACCESS_KEY=${PG_PASSWORD}
S3_BUCKET=vylux
S3_ENABLE_PATH_STYLE=1
S3_SET_ACL=0
LLM_VISION_IMAGE_USE_BASE64=1

# =====================
# Telegram (optional)
# =====================
# TELEGRAM_BOT_TOKEN=your-bot-token
EOF

echo "=== Setup Complete ==="
echo ""
echo ".env written to: $ENV_FILE"
echo ""
echo "Next steps:"
echo "  1. docker compose -f docker-compose.vylux.yml up -d"
echo "  2. Open http://localhost:3210 (LobeHub)"
echo "  3. Open http://localhost:4321 (Public Site)"
echo "  4. Create admin account in LobeHub"
echo "  5. Configure model in Settings → Model Provider"
echo ""
echo "Architecture:"
echo "  - LobeHub: http://localhost:3210 (agents, chat, admin)"
echo "  - Public Site: http://localhost:4321 (Astro + Svelte)"
echo "  - MinIO Console: http://localhost:9001 (file storage)"
echo "  - Database: ParadeDB (single instance, cms + public schemas)"
echo ""
