#!/usr/bin/env bash
# VYLUX Local Development Setup
# Generates .env with proper JWT keys and prints connection info
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$ROOT_DIR/.env"

# Generate a random 32-char JWT secret
JWT_SECRET=$(openssl rand -base64 24 | head -c 32)

# Generate Supabase-compatible JWTs
generate_jwt() {
  local role=$1
  local secret=$2
  node -e "
    const crypto = require('crypto');
    const b64url = s => Buffer.from(s).toString('base64').replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');
    const header = b64url(JSON.stringify({alg:'HS256',typ:'JWT'}));
    const body = b64url(JSON.stringify({role:'$role',iss:'supabase',iat:1700000000,exp:2000000000}));
    const sig = crypto.createHmac('sha256','$secret').update(header+'.'+body).digest('base64').replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');
    console.log(header+'.'+body+'.'+sig);
  "
}

ANON_KEY=$(generate_jwt "anon" "$JWT_SECRET")
SERVICE_ROLE_KEY=$(generate_jwt "service_role" "$JWT_SECRET")
POSTGRES_PASSWORD="vylux_dev_$(openssl rand -hex 8)"

cat > "$ENV_FILE" <<EOF
# VYLUX Local Development Environment
# Generated by scripts/setup-local.sh

# PostgreSQL
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# JWT (for PostgREST)
JWT_SECRET=${JWT_SECRET}

# Supabase-compatible keys
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

# API service
SUPABASE_URL=http://postgrest:3000
SUPABASE_ANON_KEY=${SERVICE_ROLE_KEY}
NODE_ENV=production
PORT=3000

# AI (optional — leave empty to skip)
OPENAI_API_KEY=
EOF

echo ""
echo "=== VYLUX Local Setup Complete ==="
echo ""
echo ".env written to: $ENV_FILE"
echo ""
echo "JWT_SECRET:          $JWT_SECRET"
echo "ANON_KEY:            $ANON_KEY"
echo "SERVICE_ROLE_KEY:    $SERVICE_ROLE_KEY"
echo "POSTGRES_PASSWORD:   $POSTGRES_PASSWORD"
echo ""
echo "Next steps:"
echo "  docker compose up -d"
echo "  # Wait ~30s for DB init, then:"
echo "  docker compose up -d postgrest"
echo "  # Open http://localhost:3000"
echo ""
